# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sabine Geithner
email: info@sabinegeithner.de
description: > # this means to ignore newlines until "baseurl:"
  Hello, I am Sabine Geithner - iOS Developer, Online Marketer and Biotechnologist. I work at Wire and organize UIKonf Berlin.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.sabinegeithner.de" # the base hostname & protocol for your site
twitter_username: sabinegeithner
github_username:  basine

# Build settings
markdown: kramdown
