---
title: Sabine Geithner
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@sabinegeithner.de
description: 'Hello, I am Sabine Geithner - iOS Developer, Online Marketer and Biotechnologist.
  I work at Wire and organize UIKonf Berlin.

'
baseurl: ''
url: http://www.sabinegeithner.de
twitter_username: sabinegeithner
linkedin_username: sabinegeithner
github_username: basine
markdown: kramdown
